name: Check for query-suffix tokens

on:
  push:
    paths-ignore: ['reports/**', 'build/**']
  pull_request:
    paths-ignore: ['reports/**', 'build/**']

jobs:
  fail-on-query-suffix:
    runs-on: ubuntu-latest
    name: Fail if any tracked file contains "?=NUMBER"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Search for query-suffix tokens
        id: search
        run: |
          set -euo pipefail
          # Look only at tracked files for the pattern ?=NUMBER, but ignore workflow files
          git --no-pager grep -n --full-name -I -E "\?=\d+" -- ':!/.github/workflows/*' || true

      - name: Fail if matches found
        run: |
          set -euo pipefail
          MATCHES=$(git --no-pager grep -n --full-name -I -E "\?=\d+" -- ':!/.github/workflows/*' || true)
          if [ -n "$MATCHES" ]; then
            echo "Found query-suffix tokens in tracked files:" >&2
            echo "$MATCHES" >&2
            exit 1
          else
            echo "No query-suffix tokens found in tracked files."
          fi
