name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node (optional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json, skipping npm install"
          fi

      - name: Build (if build script present)
        run: |
          if [ -f package.json ]; then
            npm run build --if-present
          else
            echo "No package.json, skipping build"
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
          publish_branch: gh-pages
          keep_files: false
